import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FloatingNavComponent } from "@/components/Nav"
import {Providers} from "@/components/Providers";
import {SiteFooter} from "@/components/Fotter";
import {MobileNav} from "@/components/MobileNav";
import React from "react";
import {PageHeader} from "@/components/PageHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >

    <Providers>
        <MobileNav/>

        <div>
            {/*<NavbarDemo />*/}
            <PageHeader />
            <FloatingNavComponent />
            <main>
                {children}
            </main>
            <SiteFooter />
        </div>
    </Providers>
      </body>
    </html>
  );
}
